gamedaoco/gamedao-haiku

- pkg/app/src/pages/app/governance.tsx
- pkg/graphql/src/query/index.ts
- pkg/graphql/src/schema/queries/bodies.graphql
> feat(add-fe-subsquid-example): added example how to retrieve chain data from graphql

- pkg/app/src/pages/app/governance.tsx
- pkg/graphql/scripts/mergeSchemas.js
- pkg/graphql/src/executors/subsquid.ts
- pkg/graphql/src/query/index.ts
- pkg/graphql/src/resolver/resolvers-types.ts
- pkg/graphql/src/schema/queries/bodies.graphql
- pkg/graphql/src/schema/schema.graphql
- pkg/graphql/src/types/index.ts
Added identity data from subsquid GraphQL.
Updated example how to use identity data.
> feat(update-subsquid-example): updated example and added identity data

- pkg/app/src/pages/app/campaigns/index.tsx
- pkg/app/src/pages/app/governance.tsx
- pkg/graphql/scripts/mergeSchemas.js
- pkg/graphql/src/executors/subsquid.ts
- pkg/graphql/src/schema/queries/campaigns.graphql
added more chain data examples to frontend.
> feat(add-more-chain-graphql-examples): updated chain data examples

- package.json
- pkg/app/src/components/OrganisationCard/itemList.tsx
- pkg/app/src/pages/app/organisations/index.tsx
- yarn.lock
Displaying the cards according to Figma design.
> Organisations List Content Area

- pkg/app/src/hooks/useLocalStorage.ts
With this PR the value is synced across multiple pages.
> fix: local storage value sync

- pkg/app/src/pages/organisations/[...param].tsx
- pkg/app/src/queries/index.ts
- pkg/app/src/queries/organizations.graphql
> feat(add-header-image): adds header image

- pkg/app/src/components/BaseDialog/baseDialog.tsx
> fix: dialog behaviour

- pkg/app/next.config.js
- pkg/app/package.json
- pkg/app/src/components/Layouts/default/modules/footer.tsx
- pkg/app/src/theme/typography.ts
> feat: add build info to footer

- pkg/app/src/components/AccountCard/accountCard.tsx
- pkg/app/src/components/AccountSelector/modules/flyout.tsx
- pkg/app/src/components/AccountSelector/modules/selector.tsx
- pkg/app/src/components/BalanceCard/balanceCard.tsx
- update colors
- reduce flyout content
- update selector
> feat: restyle account selector

- pkg/app/src/components/TabPanels/Proposal/detail.tsx
- pkg/app/src/components/TabPanels/Proposal/overview.tsx
- pkg/app/src/queries/index.ts
- pkg/app/src/queries/proposals.graphql
- pkg/app/src/theme/typography.ts
> feat(proposal-start-end-date): displayed start and end date for proposals

- pkg/app/src/components/Layouts/default/modules/sidebar.tsx
- fixes #168 
- may need additional ux thoughts if ever a scrollbar will be needed
> fix: rm scrollbars

- pkg/app/src/hooks/useIdentityByAddress.ts
- pkg/app/src/queries/identities.graphql
Changed the identity query into subscription
- Try to change your identity from polkadot.js and check if the values are changed
- Try to change your identity from the account page (/app/account) and check if the identity values will change without refreshing the page
> fix: identity subscription

- pkg/service/src/resolvers/query/displayValues/data.json
- pkg/service/src/schema.graphql
- pkg/translations/src/app/en-US.json
> feat(graphql): campaign sort options display values

- pkg/service/src/resolvers/query/displayValues/data.json
> fix(graphql): campaign sort options

- pkg/app/src/pages/organisations/index.tsx
- pkg/app/src/queries/displayValues.graphql
- pkg/service/src/resolvers/query/displayValues/data.json
- pkg/service/src/schema.graphql
> feat(graphql): campaign filters display values

- pkg/app/src/components/CampaignsSection/campaignDetailsContent.tsx
- pkg/app/src/components/TabPanels/CampaignDetails/overview.tsx
- pkg/app/src/pages/campaigns/[id].tsx
- pkg/app/src/queries/campaigns.graphql
- pkg/app/src/theme/overrides/Button.ts
- pkg/app/src/theme/overrides/Paper.ts
- pkg/translations/src/app/en-US.json
-----------------------------
Done: 
-  Campaign Details page styling
-  Campaign Details page integration with graphql to include dynamic values
- Add translation keys for campaign details page
> feat(page): campaign details page

- pkg/app/src/components/TabPanels/Proposal/overview.tsx
- pkg/app/src/pages/organisations/[...param].tsx
-----------------
- hide the create proposal button for non Dao members
> fix: hide create proposal button

- pkg/app/src/components/Account/modules/identitySection.tsx
- pkg/app/src/components/TabPanels/Organization/organizationMembers.tsx
closes #285
-----------------
Done:
- updated avatar on identity page
- updated avatar on organization members page
> feat: update avatar

- pkg/app/src/utils/campaignUtils.ts
> fix: time from block calculation

- pkg/app/src/components/TabPanels/Proposal/detail.tsx
- pkg/app/src/components/TabPanels/Proposal/overview.tsx
- pkg/app/src/hooks/tx/useSimpleVoteTransaction.ts
> fix: proposal vote

- pkg/app/src/components/TabPanels/Organization/tmpOverview.tsx
- pkg/app/src/components/TransactionDialog/transactionDialog.tsx
- pkg/app/src/utils/campaignUtils.ts
> fix: update links

- pkg/app/src/hooks/tx/useCreateProposalTransaction.ts
- pkg/app/src/queries/config.graphql
> fix: withdrawal token decimals

- pkg/service/src/resolvers/query/displayValues/data.json
Fix display values for the organization sort members
> fix: organization sort member

- pkg/app/src/components/TabPanels/Organization/tmpOverview.tsx
-------------------
- User is rerouted to organization detail page after its creation
> fix: update organization reroute

- pkg/translations/src/app/en-US.json
save on chain text instead of deploy organisation
Currently translated at 100.0% (228 of 228 strings)
Translation: GameDao/Frontend
Translate-URL: http://weblate.zero.io/projects/gamedao/frontend/en/
> chore: translated using weblate (English)

- pkg/app/src/pages/organisations/index.tsx
> fix: create organization callback

- pkg/translations/src/app/en-US.json
--------------------
Done:
- updated translation keys of creating proposal to "Proposal Created"
- updated translation keys of voting to "Voted"
> fix: proposal toasts

- pkg/app/.env.development
- pkg/app/src/@types/campaign.d.ts
- pkg/app/src/@types/campaignStatus.ts
- pkg/app/src/components/CampaignCard/campaignCard.tsx
- pkg/app/src/components/CampaignCard/modules/statusChip.tsx
- pkg/app/src/components/CampaignsList/campaignsList.tsx
- pkg/app/src/components/Forms/Campaign/form.tsx
- pkg/app/src/components/TabPanels/Campaign/create.tsx
- pkg/app/src/components/TabPanels/Campaign/overview.tsx
- pkg/app/src/hooks/useSaveCampaignDraft.ts
- pkg/app/src/hooks/useTmpCampaignState.ts
- pkg/app/src/theme/overrides/Chip.tsx
- pkg/app/src/theme/palette.ts
- pkg/translations/src/app/en-US.json
> feat(campaign-draft): add logic for campaign draft

- pkg/app/src/components/CampaignsList/campaignsList.tsx
- pkg/app/src/hooks/tx/useCreateOrgTransaction.ts
> fix: create organization

- pkg/service/src/resolvers/query/displayValues/data.json
- pkg/service/src/schema.graphql
- pkg/translations/src/app/en-US.json
> feat(#332): add tags and change countries in graphql service

- pkg/service/src/resolvers/query/displayValues/data.json
> fix: graphql types from countries and tags

- pkg/app/src/components/TabPanels/Settings/modules/about.tsx
- pkg/app/src/components/TabPanels/Settings/modules/accessType.tsx
- pkg/app/src/components/TabPanels/Settings/modules/control.tsx
- pkg/app/src/components/TabPanels/Settings/modules/memberLimit.tsx
- pkg/app/src/components/TabPanels/Settings/modules/memberType.tsx
- pkg/app/src/components/TabPanels/Settings/settings.tsx
- pkg/app/src/hooks/tx/useCreateOrgTransaction.ts
- pkg/app/src/hooks/useDisplayValues.ts
- pkg/app/src/pages/organisations/[...param].tsx
- pkg/app/src/queries/displayValues.graphql
- pkg/translations/src/app/en-US.json
> feat(#332): organisation settings page

- pkg/app/src/components/TabPanels/Settings/modules/memberType.tsx
- pkg/service/src/@types/schema.d.ts
> fix: generate new schema

- pkg/app/src/components/Charts/areaChart.tsx
- pkg/app/src/components/Charts/chart.tsx
- pkg/app/src/components/Charts/donutChart.tsx
- pkg/app/src/components/Charts/radialBar.tsx
- pkg/app/src/components/TabPanels/Organization/modules/areaChartContainer.tsx
- pkg/app/src/components/TabPanels/Organization/modules/chartContainer.tsx
- pkg/app/src/components/TabPanels/Organization/modules/radialChartContainer.tsx
- pkg/app/src/components/TabPanels/Organization/overview.tsx
- pkg/app/src/pages/organisations/[...param].tsx
- pkg/app/src/queries/organizations.graphql
- pkg/app/src/utils/campaignUtils.ts
- pkg/app/src/utils/proposalUtils.ts
- pkg/translations/src/app/en-US.json
Done:
- About section design
- Organization Rules section design
- Total members section
- Total Balance section
- Campaign statuses' percentages section
- Proposal section statuses' percentages
- Added reusable Charts components that includes:
1. Area Chart
2. Radial Chart
3. Donut Chart
> feat: organisation detail overview

- pkg/app/src/components/AccountSelector/accountSelector.tsx
- pkg/app/src/provider/extension/extensionProvider.tsx
- pkg/translations/src/app/en-US.json
> fix: fix connect logic

- pkg/app/.env
- pkg/app/.env.development
- pkg/app/src/@types/graphql.d.ts
- pkg/app/src/components/AccountSelector/modules/flyout.tsx
- pkg/app/src/components/SelectNetworkDialog/modules/networkCard.tsx
- pkg/app/src/components/SelectNetworkDialog/selectNetworkDialog.tsx
- pkg/app/src/constants/endpoints.ts
- pkg/app/src/provider/graphQl/graphQlProvider.tsx
- pkg/app/src/provider/graphQl/modules/context.ts
- pkg/app/src/provider/graphQl/modules/graphQl.ts
- pkg/app/src/provider/provider.tsx
- pkg/translations/src/app/en-US.json
> feat(network-switch): add network switch

- pkg/app/src/components/CampaignCard/campaignCard.tsx
- pkg/app/src/components/CampaignCard/modules/header.tsx
- pkg/app/src/components/Forms/Campaign/form.tsx
- pkg/app/src/components/Modals/confirmDeleteCampaignDraft.tsx
- pkg/app/src/components/TabPanels/Campaign/overview.tsx
- pkg/app/src/hooks/useSaveCampaignDraft.ts
- pkg/app/src/theme/overrides/Chip.tsx
- pkg/translations/src/app/en-US.json
> feat(delete-draft): add delete buttons and modal

- pkg/app/src/pages/organisations/[...param].tsx
> fix: update styles

- pkg/app/src/pages/organisations/[...param].tsx
> fix(org-creation): disabled click events on overlay box

- pkg/app/src/constants/endpoints.ts
- pkg/app/src/pages/organisations/[...param].tsx
> feat(network-switch-add-rococo-chain): added rococo to network switch

- pkg/app/src/components/Forms/Campaign/form.tsx
- pkg/app/src/pages/organisations/[...param].tsx
> fix(campaign-creation): fixed start date validation

- pkg/service/docker-compose-test.yml
- pkg/service/src/resolvers/query/apiProviders/apiProviderResolver.ts
- yarn.lock
> fix: block duration

- pkg/app/package.json
- pkg/app/src/components/Editor/editorWrapper.tsx
- pkg/app/src/components/Editor/index.tsx
- pkg/app/src/pages/campaigns/[id].tsx
- yarn.lock
> fix(render-editor-content): render editor content

- .gitignore
- pkg/app/src/components/TabPanels/Organization/overview.tsx
Text fix to properly reflect the correct link.
Added a git ignore line for vscode config files
> fix: fix text bug

- pkg/app/src/components/TabPanels/Proposal/detail.tsx
- pkg/app/src/constants/endpoints.ts
- pkg/app/src/constants/proposal.ts
- pkg/app/src/hooks/tx/useCreateProposalTransaction.ts
- pkg/app/src/hooks/tx/useVoteTransaction.ts
> feat(update-proposal-extrinsics): updated proposal and vote extrinsic

- pkg/app/src/components/Layouts/default/modules/header.tsx
> fix: fix header layout

- pkg/app/src/@types/campaignStatus.ts
- pkg/app/src/components/CampaignCard/modules/statusChip.tsx
- pkg/app/src/constants/campaign.ts
- pkg/app/src/hooks/tx/useCreateCampaignTransaction.ts
- pkg/app/src/theme/overrides/Chip.tsx
- pkg/service/src/resolvers/query/displayValues/data.json
- pkg/translations/src/app/en-US.json
> fix: campaign state

- pkg/app/src/queries/organizations.graphql
- pkg/squid/src/types/calls.ts
- pkg/squid/src/types/events.ts
- pkg/squid/src/types/support.ts
- pkg/squid/src/types/v62.ts
We need to add the id to each child entety so that the caching works and the hook reads the correct data from the local storage.
> fix organization caching

- pkg/app/src/components/TabPanels/Organization/overview.tsx
> fix: fix org rules

- pkg/app/src/components/Forms/Organization/modules/controller.tsx
- pkg/app/src/components/TabPanels/Settings/modules/control.tsx
> fix: fix community organizations creation

- .github/ISSUE_TEMPLATE/Bug.md
- .github/ISSUE_TEMPLATE/Task.md
> chore: update issue templates

- pkg/app/src/pages/organisations/[...param].tsx
fixes the missing treasury page, it was gone in an unfortunate merge
> fix: fix treasury page

- pkg/app/src/components/Forms/Proposal/modules/majority.tsx
- pkg/translations/src/app/en-US.json
fixes #478
I have not been able to test it yet due to the dev chain being down, but it is a simple fix, should work just fine.
> fix: fix proposals majority texts

- pkg/app/src/components/Forms/Organization/modules/settings.tsx
- pkg/app/src/components/TabPanels/Settings/modules/memberType.tsx
- pkg/translations/src/app/en-US.json
> feat: now org fee type

- pkg/app/src/layouts/default/modules/header.tsx
> fix: fixes warnings in console

- pkg/app/src/components/Forms/Organization/modules/settings.tsx
- pkg/app/src/components/TabPanels/Settings/modules/memberLimit.tsx
- pkg/app/src/components/TabPanels/Settings/modules/memberType.tsx
- pkg/translations/src/app/en-US.json
> fix: fix fields validations
